services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: 33709626
      TELEGRAM_API_HASH: a228254e1eaa22932fe7dd487a29510f
      TELEGRAM_LOCAL: "1"
    ports:
      - "8081:8081"
    volumes:
      - ./telegram-data:/var/lib/telegram-bot-api
    restart: always